---
:twitter:
  cybersecurity:
    :consumer_key: <comsumer key>
    :consumer_secret: <consumer secret>
    :access_token: <access token>
    :access_token_secret: <access token secret>
  politics:
    :consumer_key: <comsumer key>
    :consumer_secret: <consumer secret>
    :access_token: <access token>
    :access_token_secret: <access token secret>
  science:
    :consumer_key: <comsumer key>
    :consumer_secret: <consumer secret>
    :access_token: <access token>
    :access_token_secret: <access token secret>
  sports:
    :consumer_key: <comsumer key>
    :consumer_secret: <consumer secret>
    :access_token: <access token>
    :access_token_secret: <access token secret>
  default:
    :consumer_key: <comsumer key>
    :consumer_secret: <consumer secret>
    :access_token: <access token>
    :access_token_secret: <access token secret>
